### ISSUE TITLE
Error detected while processing function nvimgdb#Spawn[3]..GdbInit[1]..remote#define#request

### ISSUE THREAD

**Issue by TobyThomasTech** [sakhnik/nvim-gdb#100]
Hi. Request help in fixing this issue. I installed nvim-gdb and have installed all prerequisites. I did `UpdateRemotePlugins` and when i try to run nvim-gdb I get the following error:

```
remote/host: python3 host registered plugins ['gdb']                                                                                                                            
remote/host: generated rplugin manifest: /home/toby/.local/share/nvim/rplugin.vim                                                                                               
Error detected while processing function nvimgdb#Spawn[3]..GdbInit[1]..remote#define#request:                                                                                   
line    2:                                                                                                                                                                      
error caught in request handler '/home/toby/.config/nvim/plugged/nvim-gdb/rplugin/python3/gdb:function:GdbInit [['gdb', 'gdb_wrap.sh', 'gdb -q a.out']]':                       
Traceback (most recent call last):                                                                                                                                              
File "/home/toby/.config/nvim/plugged/nvim-gdb/rplugin/python3/gdb/__init__.py", line 28, in gdb_init                                                                         
common = BaseCommon(self.vim, self.logger, Config(self))                                                                                                                    
File "/home/toby/.config/nvim/plugged/nvim-gdb/rplugin/python3/gdb/config.py", line 50, in __init__                                                                           
self._define_signs()                                                                                                                                                        
File "/home/toby/.config/nvim/plugged/nvim-gdb/rplugin/python3/gdb/config.py", line 118, in _define_signs                                                                     
 {'text': self.config["sign_current_line"]})                                                                                                                                 
File "/usr/local/lib/python3.7/dist-packages/pynvim/api/nvim.py", line 299, in call                                                                                           
 return self.request('nvim_call_function', name, args, **kwargs)                                                                                                             
 File "/usr/local/lib/python3.7/dist-packages/pynvim/api/nvim.py", line 182, in request                                                                                        
res = self._session.request(name, *args, **kwargs)                                                                                                                          
File "/usr/local/lib/python3.7/dist-packages/pynvim/msgpack_rpc/session.py", line 102, in request                                                                             
raise self.error_wrapper(err)                                                                                                                                               
pynvim.api.common.NvimError: Vim:E117: Unknown function: sign_define
```

**Comment by sakhnik** [comment]
The function `sign_define()` was introduced in a recent version of neovim. Could you please try with a newer version of it?

**Comment by TobyThomasTech** [comment]
Thanks a lot. This fixed my issue.
