### ISSUE TITLE
`:GdbStartRR` doesn't work

### ISSUE THREAD

**Issue by amab8901** [sakhnik/nvim-gdb#178]
What are the steps to reproduce this issue?
-------------------------------------------
1. Open arbitrary file in neovim (i.e. `nvim abc`)
2. Insert command: `:GdbStartRR`
3. …

What happens?
-------------
Something opens up for a fraction of a second and immediately closes back to initial state where I was before I ran the command. 
…

What were you expecting to happen?
----------------------------------
I was expecting to get the same outcome as in the beginning of [this](https://asciinema.org/a/506942) video:
…

Any logs, error output, etc?
----------------------------------
Not any obvious ones that I'm aware of. 

This input `cd <plugin_dir>/test; CI=1 ./nvim` in terminal produces the following output:
```
bash: cd: config/nvim: No such file or directory
```

Any other comments?
-------------------
I'm new to all this, so I'm not really sure how it's supposed to work
…

**Comment by sakhnik** [comment]
Let's catch what it's showing in the terminal for a moment. Could you please repeat your attempt in a script session?
```
script nvim.log
nvim
# Try launching GdbStartRR
:q!
exit
```
There should be some trace of the failed command in the nvim.log.

**Comment by amab8901** [comment]
Here is the output:
```
Script started on 2022-10-24 15:44:45+02:00 [TERM="xterm-256color" TTY="/dev/pts/10" COLUMNS="237" LINES="26"]
]0;amab@amab-aspirea31556:~/src/playground[?2004h

[1;32m ~/src/playground [1;34m$ [m 

nvim
[?2004l
[?1049h[22;0;0t[22;0t[?1h=[H[2J]11;?[?2004h[?u[c[?25h[?25l(B[m[H[2J[>4;2m[?1004h[?25h[?25l]112[1 q[?1002h[?1006h[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[J[H[K
(B[0;1m[38;2;255;0;255m   *-----------------------------------------------------------*(B[m[K
(B[0;1m[38;2;255;0;255m   | DRY - Don't Repeat Yourself.                              |(B[m[K
(B[0;1m[38;2;255;0;255m   |                                                           |(B[m[K
(B[0;1m[38;2;255;0;255m   | Every piece of knowledge must have a single, unambiguous, |(B[m[K
(B[0;1m[38;2;255;0;255m   | authoritative representation within a system.             |(B[m[K
(B[0;1m[38;2;255;0;255m   *-----------------------------------------------------------*(B[m[K
(B[0;1m[38;2;255;0;255m          o(B[m[K
(B[0;1m[38;2;255;0;255m           o   ^__^(B[m[K
(B[0;1m[38;2;255;0;255m            o  (oo)\_______(B[m[K
(B[0;1m[38;2;255;0;255m               (__)\       )\/\(B[m[K
(B[0;1m[38;2;255;0;255m                   ||----w |(B[m[K
(B[0;1m[38;2;255;0;255m                   ||     ||(B[m[K
[K
[38;2;255;165;0m   [(B[m[38;2;255;160;160me(B[m[38;2;255;165;0m]  (B[m[38;2;128;160;255m<empty buffer>(B[m[K
[K
(B[0;1m[38;2;255;255;96m   MRU(B[m[K
[K
[38;2;255;165;0m   [(B[m[38;2;255;160;160m0(B[m[38;2;255;165;0m]  (B[m[38;2;0;255;255m~(B[m[38;2;255;165;0m/(B[m[38;2;0;255;255msrc(B[m[38;2;255;165;0m/(B[m[38;2;0;255;255mplayground(B[m[38;2;255;165;0m/(B[m[38;2;64;255;255mnvim.log(B[m[K
[38;2;255;165;0m   [(B[m[38;2;255;160;160m1(B[m[38;2;255;165;0m]  (B[m[38;2;0;255;255m~(B[m[38;2;255;165;0m/(B[m[38;2;0;255;255msrc(B[m[38;2;255;165;0m/(B[m[38;2;0;255;255mplayground(B[m[38;2;255;165;0m/(B[m[38;2;0;255;255msrc(B[m[38;2;255;165;0m/(B[m[38;2;64;255;255mmain.rs(B[m[K
[38;2;255;165;0m   [(B[m[38;2;255;160;160m2(B[m[38;2;255;165;0m]  (B[m[38;2;0;255;255m~(B[m[38;2;255;165;0m/(B[m[38;2;0;255;255m.config(B[m[38;2;255;165;0m/(B[m[38;2;0;255;255mnvim(B[m[38;2;255;165;0m/(B[m[38;2;64;255;255minit.vim(B[m[K
[38;2;255;165;0m   [(B[m[38;2;255;160;160m3(B[m[38;2;255;165;0m]  (B[m[38;2;0;255;255m~(B[m[38;2;255;165;0m/(B[m[38;2;0;255;255msrc(B[m[38;2;255;165;0m/(B[m[38;2;0;255;255mplayground(B[m[38;2;255;165;0m/(B[m[38;2;64;255;255mCargo.toml(B[m[K
[38;2;255;165;0m   [(B[m[38;2;255;160;160m4(B[m[38;2;255;165;0m]  (B[m[38;2;0;255;255m~(B[m[38;2;255;165;0m/(B[m[38;2;0;255;255msrc(B[m[38;2;255;165;0m/(B[m[38;2;0;255;255mtimer_future(B[m[38;2;255;165;0m/(B[m[38;2;0;255;255msrc(B[m[38;2;255;165;0m/(B[m[38;2;64;255;255mlib.rs(B[m[K
[38;2;255;165;0m   [(B[m[38;2;255;160;160m5(B[m[38;2;255;165;0m]  (B[m[38;2;0;255;255m~(B[m[38;2;255;165;0m/(B[m[38;2;0;255;255m.vim(B[m[38;2;255;165;0m/(B[m[38;2;0;255;255mplugged(B[m[38;2;255;165;0m/(B[m[38;2;0;255;255mvim-startify(B[m[38;2;255;165;0m/(B[m[38;2;0;255;255mtest(B[m[38;2;255;165;0m/(B[m[38;2;64;255;255mvimrc(B[m[K
(B[0;1;7m startify                                                                                                                                                                                                                                    ]112[2 q]112[2 q[15;5H[?25h[?25l[26;227H(B[m:         [15;5H[?25h[?25l
[11B[J:]112[2 q[?25h[?25lG[?25h[?25ld[?25h[?25lb[?25h[?25lS[?25h[?25lt[?25h[?25la[?25h[?25lr[?25h[?25lt[?25h[?25lR[?25h[?25lR[?25h[?25l
[26;1H[?25h[?25l]112[2 q[?25h[?25l(B[0;1m-- TERMINAL --[H(B[0;1m[38;2;255;0;255m           o   ^__^[2;4H         o  (oo)\_______(B[m[37X[3;4H(B[0;1m[38;2;255;0;255m            (__)\       )\/\(B[m[33X[4;4H(B[0;1m[38;2;255;0;255m                ||----w |(B[m[36X[5;4H(B[0;1m[38;2;255;0;255m                ||     ||(B[m[36X
[64X
[38;2;255;165;0m   [(B[m[38;2;255;160;160me(B[m[38;2;255;165;0m]  (B[m[38;2;128;160;255m<empty buffer>(B[m[42X
[11X
(B[0;1m[38;2;255;255;96m   MRU(B[m[13X
[27X
[38;2;255;165;0m   [(B[m[38;2;255;160;160m0(B[m[38;2;255;165;0m]  (B[m[38;2;0;255;255m~(B[m[38;2;255;165;0m/(B[m[38;2;0;255;255msrc(B[m[38;2;255;165;0m/(B[m[38;2;0;255;255mplayground(B[m[38;2;255;165;0m/(B[m[38;2;64;255;255mnvim.log
(B[0;7m startify                                                                                                                                                                                                                                    
(B[0;1m[38;2;255;255;0m1   (B[0;7m (B[m                       
[38;2;255;255;0m  1 
  2 (B[m                  
[38;2;255;255;0m  3 
  4 (B[m  
[38;2;255;255;0m  5 
  6 (B[m                             
[38;2;255;255;0m  7 (B[m                                
[38;2;255;255;0m  8 (B[m                           
[38;2;255;255;0m  9 (B[m                               
[38;2;255;255;0m 10 (B[m                                 
[38;2;255;255;0m 11 (B[m                                          
(B[0;1;7mterm://~/src/playground//798257:/home/amab/.vim/plugged/nvim-gdb/lib/gdb_wrap.sh -a /tmp/nvimgdb-sock-SWzmd7/port -- rr-replay.py[90C1,0-1          All[13;5H


[A[A(B[m[38;2;255;255;0m 10 (B[m [14;3H[38;2;255;255;0m9[15;3H8[16;3H7[17;3H6[19;3H4[20;3H3[21;3H2[22;3H1
(B[0;1m[38;2;255;255;0m11  (B[0;7m [24;2H(B[m[38;2;255;255;0m [23;5H[10A(B[mTraceback (most recent call last):[14;7HFile "/home/amab/.vim/plugged/nvim-gdb/lib/rr-replay.py", line 51, in <module>[15;9Hasyncio.run(run("rr replay -s0"))[16;7HFile "/usr/lib/python3.10/asyncio/runners.py", line 44, in run[17;9Hreturn loop.run_until_complete(main)[18;7HFile "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete[19;9Hreturn future.result()[20;7HFile "/home/amab/.vim/plugged/nvim-gdb/lib/rr-replay.py", line 40, in run[21;9Hraise RuntimeError("Unexpected rr replay output")[22;5HRuntimeError: Unexpected rr replay output[23;5H


[14X[13A(B[0;1m[38;2;255;255;0m1   (B[m[48;2;102;102;102m                                                                               (B[m[48;2;139;0;0m (B[m[48;2;102;102;102m                                                                                                                                                         
(B[0;1m[38;2;0;0;255m~[K
~[K
~[K
~[K
~[K
~[K
~[K
~[K
~[K
~[K
~[K
(B[0;1;7m[No Name]                                                                                                                        [90C0[13;5H[?25h[?25l[26;227H(B[m:[13;5H[?25h[?25l[26;227H 
[26;1H:]112[2 q[?25h[?25lq[?25h[?25l1[?25h[?25l
[26;1H[?25h[?25l[H(B[0;1m[38;2;255;255;0m1   (B[m[48;2;102;102;102m                                                                               (B[m[48;2;139;0;0m (B[m[48;2;102;102;102m                                                                                                                                                         
(B[0;1m[38;2;0;0;255m~[K
~[K
~[K
~[K
~[K
~[K
~[K
~[K
~[K
~[K
~[K
~[K]112[2 q[1;5H[?25h[?25l[26;227H(B[m:[1;5H[?25h[?25l
[25B[227X:]112[2 q[?25h[?25lq[?25h[?25l![?25h[?25l
[26;1H[?25h[?25l]112[2 q[?25h[?25l]112[2 q[?1002l[?1006l(B[m[?25h[?1l>[>4;0m[?1049l[23;0;0t[23;0t[?2004l[?1004l[?25h]0;amab@amab-aspirea31556:~/src/playground[?2004h

[1;32m ~/src/playground [1;34m$ [m 

exit
[?2004l
exit

Script done on 2022-10-24 15:45:04+02:00 [COMMAND_EXIT_CODE="0"]

```

Comment: When I ran `GdbStartRR`, it created a new window under the new window. The new window was full of content for a fraction of a second before immediately turning into an empty text file (not necessarily saved anywhere, kinda like when you write a new file with nvim). I had to apply `:q!` twice in order to close both windows.

**Comment by amab8901** [comment]
I managed to extract a cleaner format on the `nvim.log`:
```

   *-----------------------------------------------------*
   | All loops are infinite ones for faulty RAM modules. |
   *-----------------------------------------------------*
          o
           o   ^__^   
            o  (oo)\_______
               (__)\       )\/\
                   ||----w |
                   ||     ||

   [e]  <empty buffer>

   MRU

   [0]  ~/src/playground/src/main.rs
   [1]  ~/src/playground/nvim.log
   [2]  ~/.config/nvim/init.vim
   [3]  ~/src/playground/Cargo.toml
   [4]  ~/src/timer_future/src/lib.rs
   [5]  ~/.vim/plugged/vim-startify/test/vimrc
   [6]  ~/src/hej/src/main.rs
   [7]  ~/src/printc/Cargo.toml
   [8]  ~/src/printc/README.md

```

**Comment by sakhnik** [comment]
I've just pushed a change to the branch `develop` (https://github.com/sakhnik/nvim-gdb/commit/1ab72c623bf0199204bf566835c8d41266a6c1e8), that would leave the terminal hanging if a debugger command failed to execute.
Could you please try that revision?

**Comment by amab8901** [comment]
I applied your changes, and I did the following:
1) delete previous `nvim.log` script file
2) `nvim`
3) `GdbStartRR`

Now I finally get content displayed in the new window under the original window. Here is what it says:
```
Traceback (most recent call last):
  File "/home/amab/.vim/plugged/nvim-gdb/lib/rr-replay.py", line 51, in <module>
    asyncio.run(run("rr replay -s0"))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/amab/.vim/plugged/nvim-gdb/lib/rr-replay.py", line 40, in run
    raise RuntimeError("Unexpected rr replay output")
RuntimeError: Unexpected rr replay output

[Process exited 1]
```
Then I did the following:
4) `:q` twice to close nvim
5) `exit` to finish the scripting session
6) `tail -100 nvim.log` gives the following output:
```
 ~/*---------------------------------------------------------*
rm | Use tracer bullets to find the target.                  |
   |                                                         |
 ~/| Tracer bullets let you home in on your target by trying |
   | things and seeing how close they land.                  |
   *---------------------------------------------------------*
          o
           o   ^__^  
            o  (oo)\_______
               (__)\       )\/\
                   ||----w |
                   ||     ||                                                                                                                                                                                                                 
                                                                                                                                                                                                                                             
   [e]  <empty buffer>                                                                                                                                                                                                                       
                                                                                                                                                                                                                                             
   MRU                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                             
   [0]  ~/.vim/plugged/nvim-gdb/lua/nvimgdb/client.lua                                                                                                                                                                                       
   [1]  ~/.vim/plugged/nvim-gdb/autoload/nvimgdb.vim                                                                                                                                                                                         
   [2]  ~/src/playground/nvim.log
   [3]  ~/src/playground/src/main.rs                  
   [4]  ~/.config/nvim/init.vim                                                
   [5]  ~/src/playground/Cargo.toml   
```

**Comment by sakhnik** [comment]
What are the first lines of the output of `rr replay -s0`?

**Comment by amab8901** [comment]
> What are the first lines of the output of `rr replay -s0`?

I have Archlinux OS and `rr` is hard to install there. Are there any other options available to achieve similar outcome as `rr replay -s0`?

**Comment by amab8901** [comment]
nvm, I found a way to install `rr`

**Comment by amab8901** [comment]
Here is the output from `rr replay -s0`:

```
rr: Trace file `/home/amab/.local/share/rr/latest-trace/version' not found. There is no trace there.
```

**Comment by sakhnik** [comment]
It looks like `rr record` wasn't called before to run your program. Would the instruction in the docs help? https://github.com/sakhnik/nvim-gdb/blob/8b0a2e4d072c1451be80b1fd523942553e1e5e50/doc/nvimgdb.txt#L378

**Comment by amab8901** [comment]
> It looks like `rr record` wasn't called before to run your program. Would the instruction in the docs help?
> 
> https://github.com/sakhnik/nvim-gdb/blob/8b0a2e4d072c1451be80b1fd523942553e1e5e50/doc/nvimgdb.txt#L378
> 
> For the reference, there's the expected output:
> 
> ```
> $ rr replay -s0
> Launch gdb with
>   gdb '-l' '10000' '-ex' 'set sysroot /' '-ex' 'target extended-remote 127.0.0.1:22081' /home/sakhnik/.local/share/rr/nvim-ui-6/mmap_copy_5_nvim-ui
> ```

Thanks, the `rr` works now. Here is the output from `rr replay -s0`:
```
Launch gdb with
  gdb '-l' '10000' '-ex' 'set sysroot /' '-ex' 'target extended-remote 127.0.0.1:63274' /usr/bin/nvim

```
