### ISSUE TITLE
python3 shows tons of errors

### ISSUE THREAD

**Issue by lanza** [sakhnik/nvim-gdb#32]
Haven't figured out how to properly debug vimscript/vim-running-python to know what the errors are doing, but this pops up:

```
Error detected while processing function <SNR>165_OnBufEnter[5]..<SNR>165_GdbPaused_info_breakpoints[27]..<SNR>165_InfoBreakpoints[5]..provider#python3#Call:
line   18:
error caught in request handler 'python_eval ["InfoBreakpoints('/Users/lanza/.dotfiles/dtf', '/var/folders/p5/2m9kg46x21q8h5f9p6tpft64rm_j69/T/nvimfAJWz1/2')"]':
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/neovim/plugin/script_host.py", line 166, in python_eval
    return eval(expr, self.module.__dict__)
  File "<string>", line 1, in <module>
  File "/Users/lanza/Projects/nvim-gdb/lib/info_breakpoints.py", line 24, in InfoBreakpoints
    data, addr = sock.recvfrom(65536)
Press ENTER or type command to continue
Error detected while processing function <SNR>165_OnBufEnter[5]..<SNR>165_GdbPaused_info_breakpoints[27]..<SNR>165_InfoBreakpoints[5]..provider#python3#Call:
line   18:
socket.timeout: timed out
Press ENTER or type command to continue
Error detected while processing function <SNR>165_OnBufEnter[5]..<SNR>165_GdbPaused_info_breakpoints[29]..<SNR>165_RefreshBreakpointSigns[2]..<SNR>165_SetBreakpointSigns:
line    6:
E715: Dictionary required
Press ENTER or type command to continue
Error detected while processing function <SNR>165_OnBufEnter[5]..<SNR>165_GdbPaused_info_breakpoints[29]..<SNR>165_RefreshBreakpointSigns[2]..<SNR>165_SetBreakpointSigns:
line    6:
E714: List required
Press ENTER or type command to continue
```

**Comment by sakhnik** [comment]
I certainly haven't experienced this issue. Has it happened only once or you know how to reproduce it reliably?

**Comment by sakhnik** [comment]
The recent change 9221733d1adb5dc1526f6fc3396bb58a83eca528 improved error processing. Let me close this issue for now. Please feel free to reopen when more information is available.
